language: objective-c
osx_image: xcode8
sudo: false

rvm:
    - 2.2.2

cache:
  directories:
    - vendor/bundle

before_install:
  - bundle install --path=vendor/bundle --binstubs=vendor/bin

script:
  - bundle exec rake test
